package slidingcache

import (
	"fmt"
	"runtime"
	"sync/atomic"
	"testing"
	"time"
)

// This file replicates the production workload the cache is sized against:
// Precision 1s, WindowSize 1800s (30 min), EpochInNanos, 100k unique hashes
// where the hottest key receives up to 50k events per second and the rest sit
// at medium rates (about 1 event/s each). The benchmarks are the reference
// points stored in bench/RESULTS.md; run them via `make bench-save` to record
// a before/after pair for a change. Baseline results live in bench/ alongside
// this methodology.
//
// The full-window benchmarks iterate 180M stores per iteration and are
// designed for -benchtime=1x: they build a fresh cache per iteration so no
// event is ever late, and their cost is b.N-independent by construction.

// workloadConfig mirrors the production configuration. The janitor interval is
// raised so a sweep never lands inside a measurement; its standalone cost is
// covered by BenchmarkSweep.
func workloadConfig() Config {
	return Config{
		Precision:     time.Second,
		WindowSize:    1800 * time.Second,
		EpochUnit:     EpochInNanos,
		SweepInterval: time.Hour, // keep the janitor out of the measurement.
	}
}

// workloadBase is 2023-11-14T22:13:20Z in nanoseconds, the same anchor
// BenchmarkStoreHotKeyNanos uses. Nanosecond epochs leave int64 headroom for
// the +-3h jumps the future-jump benchmark applies.
const workloadBase = 1_700_000_000 * int64(time.Second)

// workloadKeys produces 10-char decimal keys, mirroring the production keys
// generated by strconv.FormatInt over a 64-bit tag hash.
func workloadKeys(n int) []string {
	keys := make([]string, n)
	for i := range keys {
		keys[i] = fmt.Sprintf("%010d", i)
	}
	return keys
}

// BenchmarkWorkloadHotKey50KPerSec measures the hottest key: 50k events per
// simulated second, one every 20us of nanosecond epoch. Every ~50k consecutive
// ops share a 1s bucket, so the steady-state cost is the same-bucket increment
// plus one append per simulated second; the entry stays bounded by the window
// (b.N ops span b.N*20us of simulated time, far below 1800s at default
// benchtime).
func BenchmarkWorkloadHotKey50KPerSec(b *testing.B) {
	const nanosPerEvent = 20_000
	c := newBenchCache(b, workloadConfig())
	b.ReportAllocs()
	b.ResetTimer()
	for i := range b.N {
		c.Store(workloadBase+int64(i)*nanosPerEvent, "hot-hash")
	}
}

// BenchmarkWorkload100KKeysFullWindow fills the cache to its worst-case
// footprint: 100k keys, each touched once per simulated second across the
// whole 1800s window, interleaved so the high-water mark advances globally.
// That is 180M stores per iteration (~2.1GB of live buckets), so run it at
// -benchtime=1x. It reports the sustained serial ingest throughput of the
// exact production configuration at full memory.
func BenchmarkWorkload100KKeysFullWindow(b *testing.B) {
	const (
		keys          = 100_000
		windowSeconds = 1800
	)
	keySet := workloadKeys(keys)
	b.ReportAllocs()
	for range b.N {
		c, err := New(workloadConfig())
		if err != nil {
			b.Fatalf("New returned error: %v", err)
		}
		for s := range windowSeconds {
			epoch := workloadBase + int64(s+1)*int64(time.Second)
			for k := range keys {
				c.Store(epoch, keySet[k])
			}
		}
		_ = c.Close()
	}
}

// BenchmarkWorkload100KKeysParallel measures concurrent ingest over the full
// key set. Each goroutine owns a disjoint partition of the keys and paces its
// own simulated clock at one simulated second per (keys/workers) ops, so every
// key receives one event per simulated second and goroutines stay within a few
// simulated seconds of each other (far inside the window). This models a pool
// of independent ingest workers against the default 16 shards, with no shared
// pacing counter to serialize the workers. The entry of every key grows one
// bucket per simulated second, so a default-benchtime run holds a few hundred
// MB of live buckets.
func BenchmarkWorkload100KKeysParallel(b *testing.B) {
	const keys = 100_000
	keySet := workloadKeys(keys)
	var workerIdx atomic.Int64
	c := newBenchCache(b, workloadConfig())
	b.ReportAllocs()
	b.ResetTimer()
	b.RunParallel(func(pb *testing.PB) {
		workers := runtime.GOMAXPROCS(0)
		per := keys / workers // requires keys to be divisible by GOMAXPROCS
		offset := int(workerIdx.Add(1)-1) * per
		for i := 0; pb.Next(); i++ {
			epoch := workloadBase + int64(i/per)*int64(time.Second)
			c.Store(epoch, keySet[offset+i%per])
		}
	})
}

// BenchmarkWorkloadFutureJumpRejectStorm measures the aftermath of a future
// timestamp: with the cache full at T0, one Store 3h ahead drags the global
// high-water mark forward, and every real-time Store for the next 2.5h is
// rejected by the pre-shard late check. The timed loop replays that storm --
// all ops return -1 without touching a shard -- so ns/op is the cost of the
// blackout itself, whatever the key count (10k here, for a cheap setup).
func BenchmarkWorkloadFutureJumpRejectStorm(b *testing.B) {
	const (
		keys          = 10_000
		windowSeconds = 1800
	)
	keySet := workloadKeys(keys)
	c := newBenchCache(b, workloadConfig())
	for s := range windowSeconds {
		epoch := workloadBase + int64(s+1)*int64(time.Second)
		for k := range keys {
			c.Store(epoch, keySet[k])
		}
	}
	T0 := workloadBase + windowSeconds*int64(time.Second)
	c.Store(T0+3*3600*int64(time.Second), "future-hash") // drags HW 3h ahead.
	b.ReportAllocs()
	b.ResetTimer()
	for i := range b.N {
		c.Store(T0+int64(i%windowSeconds)*int64(time.Second), keySet[i%keys])
	}
}

// BenchmarkWorkloadFootprint reports the retained heap of the worst-case
// production state: 100k keys x 1800 one-second buckets each, after GC.
// Run at -benchtime=1x. bytes/key should sit near 20.6KB (a 2048-word backing
// array plus entry, map and key overhead) and MB-live near 2.1GB.
func BenchmarkWorkloadFootprint(b *testing.B) {
	const (
		keys          = 100_000
		windowSeconds = 1800
	)
	keySet := workloadKeys(keys)
	b.ReportAllocs()
	for range b.N {
		runtime.GC()
		var before runtime.MemStats
		runtime.ReadMemStats(&before)

		c, err := New(workloadConfig())
		if err != nil {
			b.Fatalf("New returned error: %v", err)
		}
		for s := range windowSeconds {
			epoch := workloadBase + int64(s+1)*int64(time.Second)
			for k := range keys {
				c.Store(epoch, keySet[k])
			}
		}

		runtime.GC()
		var after runtime.MemStats
		runtime.ReadMemStats(&after)
		delta := after.HeapAlloc - before.HeapAlloc
		b.ReportMetric(float64(delta)/float64(keys), "bytes/key")
		b.ReportMetric(float64(delta)/(1<<20), "MB-live")

		runtime.KeepAlive(c)
		_ = c.Close()
	}
}
